# Generated by Django 6.0.3 on 2026-03-23 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_id', models.CharField(help_text='YouTube video ID, e.g. dQw4w9WgXcQ', max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration_seconds', models.IntegerField()),
                ('channel_id', models.CharField(help_text='YouTube channel ID', max_length=50)),
                ('channel_name', models.CharField(help_text='Stored for display without extra API calls', max_length=255)),
                ('category', models.CharField(blank=True, help_text='YouTube category', max_length=100, null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_text', models.TextField(blank=True, help_text='Complete transcription text', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('export_url_txt', models.URLField(blank=True, max_length=500, null=True)),
                ('export_url_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('export_url_md', models.URLField(blank=True, max_length=500, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language_code', models.ForeignKey(blank=True, db_column='language_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcriptions', to='Users.language')),
            ],
            options={
                'db_table': 'transcription',
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_order', models.IntegerField()),
                ('start_seconds', models.DecimalField(decimal_places=3, help_text='Precise start time', max_digits=8)),
                ('end_seconds', models.DecimalField(decimal_places=3, help_text='Precise end time', max_digits=8)),
                ('text', models.TextField()),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='0.0000 to 1.0000', max_digits=5, null=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='videos.transcription')),
            ],
            options={
                'db_table': 'transcript_segment',
                'ordering': ['segment_order'],
            },
        ),
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_type', models.CharField(choices=[('reference', 'Reference (free)'), ('server', 'Server (premium)')], default='reference', max_length=20)),
                ('file_url', models.URLField(blank=True, help_text='Only populated for premium server storage', max_length=500, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to='videos.video')),
            ],
            options={
                'db_table': 'user_video',
            },
        ),
        migrations.AddField(
            model_name='transcription',
            name='user_video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='videos.uservideo'),
        ),
        migrations.CreateModel(
            name='VideoCut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cut_order', models.IntegerField(help_text='Display order of the cut')),
                ('start_seconds', models.IntegerField(help_text='Cut start point in seconds')),
                ('end_seconds', models.IntegerField(help_text='Cut end point in seconds')),
                ('title', models.CharField(blank=True, help_text='AI-generated or user-set title', max_length=255, null=True)),
                ('ai_rationale', models.TextField(blank=True, help_text="AI's explanation for this cut point", null=True)),
                ('ai_suggested', models.BooleanField(default=True, help_text='Was this cut AI-suggested?')),
                ('user_approved', models.BooleanField(default=False, help_text='Has user approved this cut?')),
                ('download_url', models.URLField(blank=True, max_length=500, null=True)),
                ('download_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuts', to='videos.uservideo')),
            ],
            options={
                'db_table': 'video_cut',
                'ordering': ['cut_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='uservideo',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='unique_user_video'),
        ),
    ]
