# Generated by Django 6.0.3 on 2026-07-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='processing_stage',
            field=models.CharField(choices=[('pending', 'Queued'), ('metadata', 'Fetching video metadata'), ('transcript', 'Searching YouTube subtitles'), ('downloading', 'Downloading audio (48kbps M4A)'), ('transcribing', 'Gemini transcribing & segmenting'), ('saving', 'Saving cuts and transcript'), ('completed', 'Ready!'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
