# Generated by Django 6.0.7 on 2026-07-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_uservideo_processing_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocut',
            name='is_fallback',
            field=models.BooleanField(default=False, help_text='True if this cut was generated as a generic fallback stub'),
        ),
    ]
