# Generated by Django 6.0.7 on 2026-08-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_add_is_fallback_to_videocut'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='transcription_mode',
            field=models.CharField(choices=[('standard', 'Standard (YouTube Captions)'), ('extended', 'Extended (Gemini AI Studio)')], default='standard', help_text='Engine used to transcribe this video', max_length=20),
        ),
    ]
