# Generated by Django 6.0.7 on 2026-09-18 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_uservideo_transcription_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['transcription', 'segment_order'], name='idx_ts_transcription_order'),
        ),
        migrations.AddIndex(
            model_name='uservideo',
            index=models.Index(fields=['user', '-saved_at'], name='idx_uv_user_saved'),
        ),
        migrations.AddIndex(
            model_name='uservideo',
            index=models.Index(fields=['processing_status'], name='idx_uv_processing_status'),
        ),
        migrations.AddIndex(
            model_name='videocut',
            index=models.Index(fields=['user_video', 'cut_order'], name='idx_vc_uv_order'),
        ),
        migrations.AddIndex(
            model_name='videocut',
            index=models.Index(fields=['user_video', 'user_approved'], name='idx_vc_uv_approved'),
        ),
        migrations.AddIndex(
            model_name='videocut',
            index=models.Index(fields=['download_status'], name='idx_vc_download_status'),
        ),
    ]
