# Generated by Django 6.0.3 on 2026-03-23 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(help_text='BCP 47 code, e.g. en, fr, yo', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='English name, e.g. English, French', max_length=100)),
                ('native_name', models.CharField(help_text='Native name, e.g. Français, Yorùbá', max_length=100)),
            ],
            options={
                'db_table': 'language',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('country_code', models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 code, e.g. NG, US', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification flag')),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('language', models.ForeignKey(blank=True, help_text='Preferred UI language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Users.language')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='SocialAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(help_text='google, apple, facebook', max_length=50)),
                ('provider_uid', models.CharField(help_text='User ID from provider', max_length=255)),
                ('access_token', models.TextField(blank=True, help_text='Encrypted', null=True)),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_auths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_auth',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_uid'), name='unique_social_provider_uid')],
            },
        ),
    ]
