# Generated by Django 6.0.3 on 2026-03-23 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='free, premium', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Monthly price in USD', max_digits=10)),
                ('price_ngn', models.DecimalField(decimal_places=2, help_text='Monthly price in NGN', max_digits=12)),
                ('billing_cycle', models.CharField(help_text='monthly, yearly', max_length=20)),
                ('max_searches_per_day', models.IntegerField(default=5)),
                ('max_cuts_per_month', models.IntegerField(default=3)),
                ('max_transcriptions_per_month', models.IntegerField(default=3)),
                ('can_deep_research', models.BooleanField(default=False)),
                ('can_multi_video_chat', models.BooleanField(default=False)),
                ('can_batch_download', models.BooleanField(default=False)),
                ('can_server_storage', models.BooleanField(default=False)),
                ('has_priority_processing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscription_plan',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('trialing', 'Trialing')], default='active', max_length=20)),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('flutterwave', 'Flutterwave'), ('paystack', 'Paystack')], max_length=30)),
                ('provider_subscription_id', models.CharField(blank=True, help_text='External subscription reference', max_length=255, null=True, unique=True)),
                ('provider_customer_id', models.CharField(blank=True, help_text='External customer reference', max_length=255, null=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(help_text='USD, NGN, GBP etc.', max_length=5)),
                ('payment_provider', models.CharField(help_text='stripe, flutterwave, paystack', max_length=30)),
                ('provider_payment_id', models.CharField(help_text='External payment ID', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='Provider-specific webhook data', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Denormalized for query performance', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('search', 'Search'), ('cut', 'Cut'), ('transcription', 'Transcription'), ('research', 'Research'), ('chat_message', 'Chat Message')], max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='Related resource UUID', max_length=255, null=True)),
                ('log_date', models.DateField(help_text='Date of action (for daily limits)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage_log',
                'indexes': [models.Index(fields=['user', 'action_type', 'log_date'], name='idx_usage_log_user_date')],
            },
        ),
        migrations.CreateModel(
            name='UsageSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_date', models.DateField()),
                ('searches_count', models.IntegerField(default=0)),
                ('cuts_count', models.IntegerField(default=0)),
                ('transcriptions_count', models.IntegerField(default=0)),
                ('research_count', models.IntegerField(default=0)),
                ('chat_messages_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usage summaries',
                'db_table': 'usage_summary',
                'constraints': [models.UniqueConstraint(fields=('user', 'summary_date'), name='unique_user_summary_date')],
            },
        ),
    ]
