# Generated by Django 6.0.7 on 2026-08-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_credits_allowance',
            field=models.IntegerField(default=10, help_text='Monthly credits allocated to plan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_cuts_per_month',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_searches_per_day',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_transcriptions_per_month',
            field=models.IntegerField(default=5),
        ),
    ]
