# Generated by Django 6.0.3 on 2026-07-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsession',
            name='research_interaction_id',
            field=models.CharField(blank=True, help_text='Google Deep Research interaction ID for background polling', max_length=255, null=True),
        ),
    ]
