# Generated by Django 6.0.3 on 2026-07-21 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_researchsession_research_interaction_id'),
        ('videos', '0002_uservideo_processing_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(help_text="The user's search query")),
                ('answer', models.TextField(blank=True, help_text='AI-generated markdown answer', null=True)),
                ('follow_up_questions', models.JSONField(blank=True, default=list, help_text='List of follow-up question strings')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_sessions', to=settings.AUTH_USER_MODEL)),
                ('user_video', models.ForeignKey(blank=True, help_text='The video whose context was used for this search (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_sessions', to='videos.uservideo')),
            ],
            options={
                'db_table': 'video_search_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoSearchSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('excerpt', models.TextField(blank=True, help_text='Relevant excerpt or citation context', null=True)),
                ('rank', models.IntegerField(help_text='1-based citation order matching [N] in the answer')),
                ('search_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='chat.videosearchsession')),
            ],
            options={
                'db_table': 'video_search_source',
                'ordering': ['rank'],
            },
        ),
    ]
