# Generated by Django 6.0.7 on 2026-08-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_video_search_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosearchsession',
            name='mode',
            field=models.CharField(default='search', help_text='search or learn', max_length=20),
        ),
    ]
