# Generated by Django 6.0.7 on 2026-09-18 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_videosearchsession_mode'),
        ('videos', '0005_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_session', 'created_at'], name='idx_cm_session_created'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='idx_cs_user_updated'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['user', '-created_at'], name='idx_rs_user_created'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['status'], name='idx_rs_status'),
        ),
        migrations.AddIndex(
            model_name='videosearchsession',
            index=models.Index(fields=['user', '-created_at'], name='idx_vss_user_created'),
        ),
    ]
