# Generated by Django 6.0.3 on 2026-03-23 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Auto-generated or user-set', max_length=255, null=True)),
                ('is_multi_video', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, help_text='Token usage, model used, response time, etc.', null=True)),
                ('token_count', models.IntegerField(blank=True, help_text='For cost tracking', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Research topic/title', max_length=255, null=True)),
                ('report_content', models.TextField(blank=True, help_text='Full generated research report', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_sessions', to=settings.AUTH_USER_MODEL)),
                ('user_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_sessions', to='videos.uservideo')),
            ],
            options={
                'db_table': 'research_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('article', 'Article'), ('paper', 'Paper'), ('website', 'Website'), ('video', 'Video')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('excerpt', models.TextField(blank=True, help_text='Relevant excerpt from source', null=True)),
                ('relevance_rank', models.IntegerField(help_text='Ordering by relevance')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('research_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='chat.researchsession')),
            ],
            options={
                'db_table': 'research_source',
                'ordering': ['relevance_rank'],
            },
        ),
        migrations.CreateModel(
            name='VideoRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommended_youtube_id', models.CharField(max_length=20)),
                ('recommended_title', models.CharField(max_length=500)),
                ('recommended_thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('recommendation_type', models.CharField(choices=[('related_video', 'Related Video'), ('related_article', 'Related Article')], max_length=20)),
                ('relevance_score', models.DecimalField(blank=True, decimal_places=4, help_text='0.0000 to 1.0000', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_user_video', models.ForeignKey(help_text='The video that generated this recommendation', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='videos.uservideo')),
            ],
            options={
                'db_table': 'video_recommendation',
            },
        ),
        migrations.CreateModel(
            name='ChatSessionVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_order', models.IntegerField(help_text='Order in which videos were added')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_videos', to='chat.chatsession')),
                ('user_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='videos.uservideo')),
            ],
            options={
                'db_table': 'chat_session_video',
                'constraints': [models.UniqueConstraint(fields=('chat_session', 'user_video'), name='unique_chat_session_video')],
            },
        ),
    ]
