# Generated by Django 6.0.7 on 2026-08-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits_balance',
            field=models.IntegerField(default=10, help_text='Available AI credits balance'),
        ),
    ]
